Get Data from the following link: http://files.grouplens.org/datasets/movielens/ml-20m.zip
We will be using the following files for this exercise:
ratings.csv : userId,movieId,rating, timestamp
tags.csv : userId,movieId, tag, timestamp
movies.csv : movieId, title, genres
1. Read the dataset using pandas.
2. Extract the first row from tags and print its type.
3. Extract row 0, 11, 2000 from tags DataFrame.
4. Print index, columns of the DataFrame.
5. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().
6. Filter out ratings with rating > 5
7. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.
8. Filter out movies from the movies DataFrame that are of type 'Animation'.
9. Find the average rating of movies.
10. Perform an inner join of movies and tags based on movieId.
11. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.
12. Split 'genres' into multiple columns.
13. Extract year from title e.g. (1995).
14. Select rows based on timestamps later than 2015-02-01.
15. Sort the tags DataFrame based on timestamp.

1. Read the dataset using pandas.

In [2]:
import pandas as pd

In [9]:
ratings=pd.read_csv("ratings.csv")

In [1]:
tags=pd.read_csv("tags.csv")

NameError: name 'pd' is not defined

In [11]:
movies=pd.read_csv("movies.csv")

2. Extract the first row from tags and print its type.

In [14]:
data=tags.head(1)
print(data)
type(data)

   userId  movieId          tag   timestamp
0      18     4141  Mark Waters  1240597180

pandas.core.frame.DataFrame

3. Extract row 0, 11, 2000 from tags DataFrame.

In [15]:
tags.iloc[[1,11,2000],:]

      userId  movieId                tag   timestamp
1         65      208          dark hero  1368150078
11        65     1783      noir thriller  1368149983
2000     910    68554  conspiracy theory  1368043943

4. Print index, columns of the DataFrame.

In [16]:
print("****************************\n index, columns of the ratings dataframe \n ****************************")
ratings.info()
print("****************************\n index, columns of the tags dataframe \n ****************************")
tags.info()
print("****************************\n index, columns of the movies dataframe \n ****************************")
movies.info()

****************************
 index, columns of the ratings dataframe
 ****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 4 columns):
userId       int64
movieId      int64
rating       float64
timestamp    int64
dtypes: float64(1), int64(3)
memory usage: 610.4 MB
****************************
 index, columns of the tags dataframe
 ****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465564 entries, 0 to 465563
Data columns (total 4 columns):
userId       465564 non-null int64
movieId      465564 non-null int64
tag          465548 non-null object
timestamp    465564 non-null int64
dtypes: int64(3), object(1)
memory usage: 14.2+ MB
****************************
 index, columns of the movies dataframe
 ****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
movieId    27278 non-null int64
title      27278 non-null object
genres     27278 non-null object
dtypes: int64(1), object(2)
memory usage: 639.4+ KB

5. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().

In [17]:
print("individual calculations over rating column")
print("countc:",ratings.rating.count())
print("Mean:",ratings.rating.mean())
print("Std:",ratings.rating.std())
print("Min:",ratings.rating.min())
print("Max:",ratings.rating.max())
print("using decribe function")
ratings.rating.describe()

individual calculations over rating column
countc: 20000263
Mean: 3.5255285642993797
Std: 1.051988919275684
Min: 0.5
Max: 5.0
using decribe function

count    2.000026e+07
mean     3.525529e+00
std      1.051989e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

6. Filter out ratings with rating > 5

In [18]:
ratings[ratings["rating"]>=5]

          userId  movieId  rating   timestamp
131            1     4993     5.0  1112484682
142            1     5952     5.0  1112484619
158            1     7153     5.0  1112484633
170            1     8507     5.0  1094786027
176            2       62     5.0   974820598
177            2       70     5.0   974820691
180            2      260     5.0   974821014
181            2      266     5.0   974820748
183            2      480     5.0   974820720
184            2      541     5.0   974821014
185            2      589     5.0   974820658
188            2      924     5.0   974821014
190            2     1196     5.0   974821014
191            2     1210     5.0   974820598
192            2     1214     5.0   974821014
193            2     1249     5.0   974820691
194            2     1259     5.0   974820659
195            2     1270     5.0   974821014
196            2     1327     5.0   974820846
197            2     1356     5.0   974820598
198            2     1544     5.0   974820943
201            2     1748     5.0   974821014
208            2     1974     5.0   974820598
215            2     2948     5.0   974820659
220            2     3450     5.0   974820846
221            2     3513     5.0   974820659
231            2     3927     5.0   974820748
232            2     3928     5.0   974820776
233            2     3930     5.0   974820943
235            2     3959     5.0   974820659
...          ...      ...     ...         ...
20000138  138493     6377     5.0  1256750400
20000145  138493     6711     5.0  1255817636
20000148  138493     6807     5.0  1255809702
20000150  138493     6874     5.0  1255806503
20000153  138493     6942     5.0  1255809672
20000155  138493     7008     5.0  1255809318
20000156  138493     7060     5.0  1258134307
20000157  138493     7090     5.0  1255805219
20000161  138493     7293     5.0  1255817269
20000164  138493     7361     5.0  1255807607
20000165  138493     7371     5.0  1256288607
20000167  138493     7438     5.0  1255806506
20000169  138493     8254     5.0  1255805322
20000178  138493     8905     5.0  1255856919
20000181  138493     8973     5.0  1255811257
20000184  138493    26422     5.0  1256680286
20000185  138493    26776     5.0  1255805879
20000190  138493    27773     5.0  1255806599
20000202  138493    33903     5.0  1255816555
20000209  138493    39183     5.0  1255806612
20000217  138493    44555     5.0  1255806360
20000223  138493    47465     5.0  1256680620
20000225  138493    48082     5.0  1258390139
20000228  138493    48385     5.0  1255817767
20000229  138493    48516     5.0  1255815874
20000230  138493    48780     5.0  1255804799
20000244  138493    55269     5.0  1255816088
20000245  138493    55814     5.0  1255811181
20000251  138493    59784     5.0  1255816901
20000261  138493    70286     5.0  1258126944

[2898660 rows x 4 columns]

7. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.

In [19]:
print("***Count NaN, missing values in each column of a Ratings DataFrame***")
print("Nan in each columns" , ratings.isnull().sum(), sep='\n')
print("***Count NaN, missing values in each column of a Tags DataFrame***")
print("Nan in each columns" , tags.isnull().sum(), sep='\n')
print("***Count NaN, missing values in each column of a Movies DataFrame***")
print("Nan in each columns" , movies.isnull().sum(), sep='\n')

print("Filling Null or missing values with Santosh")
Dataset=tags.fillna("Santosh")
print("Modified row count is\n",Dataset[Dataset["tag"]=="Santosh"].count())

***Count NaN, missing values in each column of a Ratings DataFrame***
Nan in each columns
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64
***Count NaN, missing values in each column of a Tags DataFrame***
Nan in each columns
userId        0
movieId       0
tag          16
timestamp     0
dtype: int64
***Count NaN, missing values in each column of a Movies DataFrame***
Nan in each columns
movieId    0
title      0
genres     0
dtype: int64
Filling Null or missing values with Santosh
Modified row count is
 userId       16
movieId      16
tag          16
timestamp    16
dtype: int64

8. Filter out movies from the movies DataFrame that are of type 'Animation'.

In [20]:
df = movies[movies['genres']!='Animation']

print(df)

       movieId                                              title  \
0            1                                   Toy Story (1995)
1            2                                     Jumanji (1995)
2            3                            Grumpier Old Men (1995)
3            4                           Waiting to Exhale (1995)
4            5                 Father of the Bride Part II (1995)
5            6                                        Heat (1995)
6            7                                     Sabrina (1995)
7            8                                Tom and Huck (1995)
8            9                                Sudden Death (1995)
9           10                                   GoldenEye (1995)
10          11                     American President, The (1995)
11          12                 Dracula: Dead and Loving It (1995)
12          13                                       Balto (1995)
13          14                                       Nixon (1995)
14          15                            Cutthroat Island (1995)
15          16                                      Casino (1995)
16          17                       Sense and Sensibility (1995)
17          18                                  Four Rooms (1995)
18          19              Ace Ventura: When Nature Calls (1995)
19          20                                 Money Train (1995)
20          21                                  Get Shorty (1995)
21          22                                     Copycat (1995)
22          23                                   Assassins (1995)
23          24                                      Powder (1995)
24          25                           Leaving Las Vegas (1995)
25          26                                     Othello (1995)
26          27                                Now and Then (1995)
27          28                                  Persuasion (1995)
28          29  City of Lost Children, The (Cité des enfants p...
29          30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...
...        ...                                                ...
27248   131146                      Werner - Volles Rooäää (1999)
27249   131148                                  What A Man (2011)
27250   131150         7 Dwarves: The Forest Is Not Enough (2006)
27251   131152                                 The Fat Spy (1966)
27252   131154  Die Bademeister – Weiber, saufen, Leben retten...
27253   131156                         Ants in the Pants 2 (2002)
27254   131158                                Manta, Manta (1991)
27255   131160                  Oscar and the Lady in Pink (2009)
27256   131162                      Por un puñado de besos (2014)
27257   131164                               Vietnam in HD (2011)
27258   131166                                  WWII IN HD (2009)
27259   131168                                     Phoenix (2014)
27260   131170                                   Parallels (2015)
27261   131172                              Closed Curtain (2013)
27262   131174                                   Gentlemen (2014)
27263   131176                             A Second Chance (2014)
27264   131180                     Dead Rising: Watchtower (2015)
27265   131231                                     Standby (2014)
27266   131237                         What Men Talk About (2010)
27267   131239                          Three Quarter Moon (2011)
27268   131241                           Ants in the Pants (2000)
27269   131243                Werner - Gekotzt wird später (2003)
27270   131248                              Brother Bear 2 (2006)
27271   131250                              No More School (2000)
27272   131252  Forklift Driver Klaus: The First Day on the Jo...
27273   131254                       Kein Bund für's Leben (2007)
27274   131256                      Feuer, Eis & Dosenbier (2002)
27275   131258                                 The Pirates (2014)
27276   131260                                Rentun Ruusu (2001)
27277   131262                                   Innocence (2014)

                                            genres
0      Adventure|Animation|Children|Comedy|Fantasy
1                       Adventure|Children|Fantasy
2                                   Comedy|Romance
3                             Comedy|Drama|Romance
4                                           Comedy
5                            Action|Crime|Thriller
6                                   Comedy|Romance
7                               Adventure|Children
8                                           Action
9                        Action|Adventure|Thriller
10                            Comedy|Drama|Romance
11                                   Comedy|Horror
12                    Adventure|Animation|Children
13                                           Drama
14                        Action|Adventure|Romance
15                                     Crime|Drama
16                                   Drama|Romance
17                                          Comedy
18                                          Comedy
19              Action|Comedy|Crime|Drama|Thriller
20                           Comedy|Crime|Thriller
21             Crime|Drama|Horror|Mystery|Thriller
22                           Action|Crime|Thriller
23                                    Drama|Sci-Fi
24                                   Drama|Romance
25                                           Drama
26                                  Children|Drama
27                                   Drama|Romance
28          Adventure|Drama|Fantasy|Mystery|Sci-Fi
29                                     Crime|Drama
...                                            ...
27248                             Animation|Comedy
27249                               Comedy|Romance
27250                                       Comedy
27251                                       Comedy
27252                                       Comedy
27253                                       Comedy
27254                                       Comedy
27255                                        Drama
27256                                Drama|Romance
27257                                          War
27258                           (no genres listed)
27259                                        Drama
27260                                       Sci-Fi
27261                           (no genres listed)
27262                       Drama|Romance|Thriller
27263                                        Drama
27264                       Action|Horror|Thriller
27265                               Comedy|Romance
27266                                       Comedy
27267                                 Comedy|Drama
27268                               Comedy|Romance
27269                             Animation|Comedy
27270  Adventure|Animation|Children|Comedy|Fantasy
27271                                       Comedy
27272                                Comedy|Horror
27273                                       Comedy
27274                                       Comedy
27275                                    Adventure
27276                           (no genres listed)
27277                     Adventure|Fantasy|Horror

[27195 rows x 3 columns]

9. Find the average rating of movies.

In [21]:
print("Average rating of the movies:",ratings.rating.mean())

Average rating of the movies: 3.5255285642993797

10. Perform an inner join of movies and tags based on movieId.

In [22]:
movies.join(tags,on='movieId',how='inner',lsuffix='Mov')

,movieIdMov,title,genres,userId,movieId,tag,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,65,208,dark hero,1368150078
1,2,Jumanji (1995),Adventure|Children|Fantasy,65,353,dark hero,1368150079
2,3,Grumpier Old Men (1995),Comedy|Romance,65,521,noir thriller,1368149983
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,65,592,dark hero,1368150078
4,5,Father of the Bride Part II (1995),Comedy,65,668,bollywood,1368149876
5,6,Heat (1995),Action|Crime|Thriller,65,898,screwball comedy,1368150160
6,7,Sabrina (1995),Comedy|Romance,65,1248,noir thriller,1368149983
7,8,Tom and Huck (1995),Adventure|Children,65,1391,mars,1368150055
8,9,Sudden Death (1995),Action,65,1617,neo-noir,1368150217
9,10,GoldenEye (1995),Action|Adventure|Thriller,65,1694,jesus,1368149925
10,11,"American President, The (1995)",Comedy|Drama|Romance,65,1783,noir thriller,1368149983
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,65,2022,jesus,1368149925
12,13,Balto (1995),Adventure|Animation|Children,65,2193,dragon,1368151314
13,14,Nixon (1995),Drama,65,2353,conspiracy theory,1368151266
14,15,Cutthroat Island (1995),Action|Adventure|Romance,65,2662,mars,1368150055
15,16,Casino (1995),Crime|Drama,65,2726,noir thriller,1368149983
16,17,Sense and Sensibility (1995),Drama|Romance,65,2840,jesus,1368149925
17,18,Four Rooms (1995),Comedy,65,3052,jesus,1368149926
18,19,Ace Ventura: When Nature Calls (1995),Comedy,65,5135,bollywood,1368149876
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,65,6539,treasure,1368149949
20,21,Get Shorty (1995),Comedy|Crime|Thriller,65,6874,dark hero,1368150079
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,65,7013,noir thriller,1368149983
22,23,Assassins (1995),Action|Crime|Thriller,65,7318,jesus,1368149925
23,24,Powder (1995),Drama|Sci-Fi,65,8529,stranded,1368150012
24,25,Leaving Las Vegas (1995),Drama|Romance,65,8622,conspiracy theory,1368151266
25,26,Othello (1995),Drama,65,27803,Oscar (Best Foreign Language Film),1305008715
26,27,Now and Then (1995),Children|Drama,65,27866,New Zealand,1304957153
27,28,Persuasion (1995),Drama|Romance,65,48082,surreal,1304958354
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,65,48082,unusual,1304958359
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,65,51884,bollywood,1368149876
...,...,...,...,...,...,...,...
27248,131146,Werner - Volles Rooäää (1999),Animation|Comedy,34494,53956,Nudity (Rear),1326402278
27249,131148,What A Man (2011),Comedy|Romance,34494,53956,wheelchair,1326402295
27250,131150,7 Dwarves: The Forest Is Not Enough (2006),Comedy,34494,56719,prodigy,1326535978
27251,131152,The Fat Spy (1966),Comedy,34494,58998,break-up,1327260156
27252,131154,"Die Bademeister – Weiber, saufen, Leben retten...",Comedy,34494,58998,Hawaii,1327260176
27253,131156,Ants in the Pants 2 (2002),Comedy,34494,58998,jealousy,1327260186
27254,131158,"Manta, Manta (1991)",Comedy,34494,58998,Nudity (Full Frontal - Notable),1327260193
27255,131160,Oscar and the Lady in Pink (2009),Drama,34494,58998,puppets,1327260247
27256,131162,Por un puñado de besos (2014),Drama|Romance,34494,58998,surfing,1327260243
27257,131164,Vietnam in HD (2011),War,34494,60069,Comedy,1322934956
27258,131166,WWII IN HD (2009),(no genres listed),34494,60069,robots,1322934947
27259,131168,Phoenix (2014),Drama,34494,60408,hilarious,1322934874
27260,131170,Parallels (2015),Sci-Fi,34494,61323,Brad Pitt,1326646054
27261,131172,Closed Curtain (2013),(no genres listed),34494,61323,cosmetic surgery,1326646075
27262,131174,Gentlemen (2014),Drama|Romance|Thriller,34494,61323,George Clooney,1326646092
27263,131176,A Second Chance (2014),Drama,34494,61323,John Malkovich,1326646067
27264,131180,Dead Rising: Watchtower (2015),Action|Horror|Thriller,34494,64614,Clint Eastwood,1323542837
27265,131231,Standby (2014),Comedy|Romance,34494,73587,sexuality,1323469711
27266,131237,What Men Talk About (2010),Comedy,34494,76093,dragons,1325326591
27267,131239,Three Quarter Moon (2011),Comedy|Drama,34494,76093,friendship,1325326636
27268,131241,Ants in the Pants (2000),Comedy|Romance,34494,77191,dark comedy,1326402404
27269,131243,Werner - Gekotzt wird später (2003),Animation|Comedy,34494,77191,male nudity,1326402427
27270,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy,34494,78321,sexuality,1326228885
27271,131250,No More School (2000),Comedy,34494,79132,alternate reality,1325326442
27272,131252,Forklift Driver Klaus: The First Day on the Jo...,Comedy|Horror,34494,79132,dreamlike,1325326562
27273,131254,Kein Bund für's Leben (2007),Comedy,34494,79132,fantasy,1325326456
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,34494,79132,Leonardo DiCaprio,1325326461
27275,131258,The Pirates (2014),Adventure,34494,79132,sci-fi,1325326474
27276,131260,Rentun Ruusu (2001),(no genres listed),34494,79132,thought-provoking,1325326483
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,34494,79590,AGE DISPARITY ROMANCE,1326319089

11. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.

In [23]:
Df1 = movies.join(ratings,on='movieId',how='inner',lsuffix='Mov')
df2 = Df1[(Df1['genres']=='Comedy') & (Df1['rating']>4.0)]
df2.head(5)

MemoryError: cannot allocate memory for array

12. Split 'genres' into multiple columns.

In [ ]:
df = movies['genres'].str.split('|').tolist()

generes_columns=pd.DataFrame(df,columns=['generes1', 'generes2','generes3','generes4','generes5','generes6','generes7','generes8','generes9','generes10'])
generes_columns

13. Extract year from title e.g. (1995).

In [ ]:
df=movies['title'].str[-6:]
df

14. Select rows based on timestamps later than 2015-02-01.

In [ ]:
import datetime

df=ratings
df['timestamp'] = pd.to_datetime(df['timestamp']).dt.date
D=datetime.date(2015,2,1)
res=df[df['timestamp'] > D]
res

15. Sort the tags DataFrame based on timestamp.

In [ ]:
df = tags.sort_values(by='timestamp',ascending=True)
df